Draft: Speed improvements
netbox-community/pynetbox pull request #659
Opened 2024-12-04 21:05 UTC by srfwx

### Fixes: #658 

Various refactoring allows for a substantial increase in performance of the Record initialization.

- `_parse_values` was heavily refactored to avoid multiple similar checks and unnecessary processing
- in turn, `get_return` now only needs to work on `Record` object and drops legacy code from Netbox 2.7
- `_endpoint_from_url` can work with string instead of using the `urlsplit` library
- finally caching of apps/endpoints avoid constant reinstantiation of similar objects

Automated tests are currently not passing (although real world usage does work) but I am not entirely sure how to best fix this at this point.
```
FAILED tests/unit/test_response.py::RecordTestCase::test_endpoint_from_url - AssertionError: <Mock name='mock.test-app.test-endpoint.name' id='134373396458000'> != 'test-endpoint'
FAILED tests/unit/test_response.py::RecordTestCase::test_endpoint_from_url_with_directory_in_base_url - AssertionError: <Mock name='mock.test-app.test-endpoint.name' id='134373396560384'> != 'test-endpoint'
FAILED tests/unit/test_response.py::RecordTestCase::test_endpoint_from_url_with_plugins - AssertionError: <Mock name='mock.plugins.test-app.test-endpoint.name' id='134373422589328'> != 'test-endpoint'
FAILED tests/unit/test_response.py::RecordTestCase::test_endpoint_from_url_with_plugins_and_directory_in_base_url - AssertionError: <Mock name='mock.plugins.test-app.test-endpoint.name' id='134373396320976'> != 'test-endpoint'
FAILED tests/unit/test_response.py::RecordTestCase::test_nested_write - TypeError: 'Mock' object is not subscriptable
FAILED tests/unit/test_response.py::RecordTestCase::test_nested_write_with_directory_in_base_url - TypeError: 'Mock' object is not subscriptable

```

2024-12-10 16:37 UTC, srfwx commented
@arthanson the size of this PR may have gotten a little bit out of hand.
I assume you may want to break it into into smaller changes.

As a summary here is what's been implemented so far:

- Cache of Endpoints on App
- Cache nested Records on Endpoints
- Adds class ValueRecord for dict that don't include an endpoint (contrary to class Record)
- Improves speed of computation of endpoint from URL
- Lazy computation of Record.endpoint
- Improves value parsing performance and readability

Please let me know what you think and what you'd like to possibly see as individual PR.

2025-05-14 15:00 UTC, arthanson requested changes

2025-05-14 15:00 UTC, arthanson commented on pynetbox/models/mapper.py
> +TYPE_CONTENT_MAPPER = {v: k for k, v in CONTENT_TYPE_MAPPER.items() if v is not None}
What is this for? I don't see it used anywhere?

2025-05-14 15:00 UTC, arthanson commented on pynetbox/models/dcim.py
> +    device = Devices
Can you put this in a separate PR, it doesn't look like a speed improvement but a bug fix (if a bug fix and there isn't an issue for it, please open an issue).

2025-05-14 15:00 UTC, arthanson commented on pynetbox/core/endpoint.py
> +        self._init_cache()
This is only called in one place and has a function defined for it - can you just put it inline with a comment instead, not sure why we need a separate function for this?

2025-05-14 15:00 UTC, arthanson commented on pynetbox/core/endpoint.py
> +class CachedRecordRegistry:
Maybe? Split this and the one in core/app.py into two separate PR's?  Although both are caching - the seem like functionally separate functionality that can be reviewed separately (and potentially backed out separately if any issues).

2025-06-12 15:19 UTC, jnovinger commented
@srfwx , can you address/answer Arthur's concerns/questions? Otherwise, we'll need to close this out as stale work before too long.

2025-06-12 16:49 UTC, srfwx commented
Hi @jnovinger ,
Yes sure, I'll get to it as soon as possible.
Note that it took 5 months to get initial feedback so as you can imagine I've switched to other topics in the meantime... But I'll try to allocate time for this in the coming couple of weeks if that's alright

2025-07-25 14:48 UTC, srfwx commented
Hi @jnovinger, @arthanson  I am sorry to inform you that I won't be able to commit time to this before beginning of September at the earliest. I will definitely get the work done to get this merged. Thank you for your patience.

2025-07-25 16:00 UTC, arthanson commented
Thank for getting back. I'll go ahead and close this for now @srfwx please reopen when you are ready to get back to it.

2025-07-25 16:00 UTC, closed without merging